#!/bin/sh

# Install Minimal Prerequisites
sudo apt update && sudo apt install -y cmake unzip g++ wget clang libclang-dev libopencv-dev libopencv-videoio-dev

# Install webcam
cargo install ascii-webcam
