#!/bin/bash

# Install gh cli
(type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
        && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y

# Install Development stuff
sudo apt install -y luarocks ruby-full golang python3 python3-venv iredis docker.io zsh unixodbc unixodbc-dev tmux php-cli default-jre default-jdk libtree-sitter-dev perl

# Install gh command line
(type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
        && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y

# Install php composer
curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install --lts
nvm use --lts

# Install treesitter-cli
npm install -g tree-sitter-cli

# Add current user to docker
sudo usermod -aG docker $USER

# Install Deno
curl -fsSL https://deno.land/install.sh | sh

# Source files...
source ~/.bash_profile
source ~/.profile

# Install taskbook (for note taking on cli)
deno install -g npm:taskbook

# Install usql (universal sql cli)
go install -tags all github.com/xo/usql@master

# Install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Add zsh syntax highlighting to the zshrc
sed -i 's/\(plugins=(.*)\)/\1 zsh-syntax-highlighting)/' ~/.zshrc

# Install zsh autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Add zsh autosuggestions to the zshrc
sed -i 's/\(plugins=(.*)\)/\1 zsh-autosuggestions)/' ~/.zshrc

# Install zsh autoswitch virtualenv
git clone "https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git" "$ZSH_CUSTOM/plugins/autoswitch_virtualenv"

# Add zsh autoswitch virtualenv to the zshrc
sed -i 's/\(plugins=(.*)\)/\1 autoswitch_virtualenv)/' ~/.zshrc

# Add sudo to the zshrc
sed -i 's/\(plugins=(.*)\)/\1 sudo)/' ~/.zshrc

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install Tauri dependencies
sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

# Install Tauri
cargo install create-tauri-app --locked

# Install Tauri CLI
cargo install tauri-cli --version '^2.0.0' --locked

# Install Trunk
cargo install trunk --locked

# Add wasm target
rustup target add wasm32-unknown-unknown
