#!/bin/sh

# Install dependencies
sudo apt install -y j4-dmenu-desktop libxkbcommon-x11-dev xterm alacritty xorg build-essential libx11-dev libxinerama-dev libxft-dev libwebkit2gtk-4.1-dev

# Get CPU Core count
num_cores=$(nproc)

# Install DWM
sudo make -C "$DEV_ENV_HOME/dwm" clean install -j"$num_cores"

# Install DMENU
sudo make -C "$DEV_ENV_HOME/dmenu" clean install -j"$num_cores"
