#!/bin/sh

sudo apt -y update
sudo apt -y install zip pulsemixer unzip curl wget git apt-transport-https ca-certificates software-properties-common ripgrep xclip jq tldr shutter python3-pip shellcheck mpv ffmpeg brotli 7zip meson ninja-build

git clone https://github.com/junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install
