#!/bin/bash

# Install lxappearance
sudo apt install -y lxappearance

# Download Icon Theme
wget https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip

# Unzip Icon Theme
unzip master.zip

# Move Icon Theme
sudo mv candy-icons-master /usr/share/icons/

# Remove zip
rm -rf master.zip

# Download GTK Theme
wget https://github.com/EliverLara/Sweet/releases/download/v5.0/Sweet-Dark-v40.tar.xz

# Untar GTK Theme
tar -xvf Sweet-Dark-v40.tar.xz

# Move GTK Theme
sudo mv Sweet-Dark-v40 /usr/share/themes/

# Remove tar
rm -rf Sweet-Dark-v40.tar.xz
