#!/bin/sh

# Install preload
sudo pacman -S --noconfirm preload

# Disable plymouth
sudo sed -i 's#^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$#GRUB_CMDLINE_LINUX_DEFAULT="fsck.mode=skip quiet"#g' /etc/default/grub

# Uninstall snaps
sudo pacman -Rns --noconfirm snapd && rm -rf ~/snap && sudo rm -rf /snap /var/snap /var/lib/snapd

# Don't let the network stall the boot process
sudo systemctl disable NetworkManager-wait-online.service
