#!/bin/sh

# Install flatpak
sudo zypper install -l flatpak

# Add flathub repository
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Add gnome software plugin flatpak
sudo zypper install -l gnome-software gnome-software-plugin-flatpak

