#!/bin/bash

# Install dependencies for picom
# Package names are openSUSE equivalents
sudo zypper install -y -l libXext-devel libxcb-devel libpixman-1-0-devel dbus-1-devel libconfig-devel Mesa-libGL-devel pcre2 libevdev-devel uthash-devel libev-devel xcb-util-image-devel xcb-util-renderutil-devel libX11-devel meson ninja git

# Get picom with animations
git clone https://gitlab.com/phyos/picom.git $HOME/picom

# Build picom
cd $HOME/picom || exit
git submodule update --init --recursive
meson --buildtype=release . build
ninja -C build
sudo ninja -C build install

echo "Picom installation attempted."

