#!/bin/sh

# Disable plymouth
sudo sed -i 's#^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$#GRUB_CMDLINE_LINUX_DEFAULT="fsck.mode=skip quiet"#g' /etc/default/grub

# Uninstall snaps
sudo zypper remove snapd && rm -rf ~/snap && sudo rm -rf /snap /var/snap /var/lib/snapd && sudo zypper addlock snapd

# Don't let the network stall the boot process
sudo systemctl disable NetworkManager-wait-online.service
